// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iscjistruuqqmxgnpwxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzY2ppc3RydXVxcW14Z25wd3h3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2OTA2MzUsImV4cCI6MjA2MjI2NjYzNX0._GQj9uuzpG1yhT36Hfhe7JDHwJ9NfiHJIilUgTbO1-I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);